import {BarChart3,FileText,ShieldCheck} from 'lucide-react';
import EDADashboard from './EDADashboard';
import type {Job} from './types';

const fmt=(value:unknown):string=>value==null?'—':typeof value==='number'?value.toLocaleString(undefined,{maximumFractionDigits:5}):typeof value==='object'?JSON.stringify(value):String(value);
const SECTIONS=[['overview','Problem & summary'],['quality','Data quality'],['eda','EDA & charts'],['preparation','Cleaning & features'],['models','Model comparison'],['evaluation','Evaluation'],['shap','Explainability'],['recommendations','Next steps']];

export default function MainReport({job,apiKey}:{job:Job;apiKey:string}){
  const r=job.result;
  if(!r)return null;
  const {profile,cleaning,features,models,evaluation,explainability,insights}=r;
  const metricRows=Object.entries(evaluation.metrics).filter(([,v])=>typeof v==='number'||v===null);
  const confusion=evaluation.metrics.confusion_matrix as number[][]|undefined;
  return <article className="main-report" aria-label="Main analysis report">
    <nav className="report-contents" aria-label="Main report contents">{SECTIONS.map(([id,label],i)=><a key={id} href={`#report-${id}`}><span>{i+1}</span>{label}</a>)}</nav>
    <section className="surface report-section" id="report-overview">
      <div className="section-title"><FileText size={21}/><h2>1. Problem & executive summary</h2><span className="pill push">{r.plan.task}</span></div>
      <p className="report-goal">{job.request.goal}</p>
      <div className="report-facts"><div><span>Dataset</span><strong>{job.dataset_filename||'Saved dataset'}</strong></div><div><span>Target</span><strong>{r.plan.target||'No target (clustering)'}</strong></div><div><span>Selected model</span><strong>{models.winner}</strong></div><div><span>Analysis created</span><strong>{new Date(job.created*1000).toLocaleString()}</strong></div></div>
      <p>{insights.summary}</p><p className="muted small">This report combines the uploaded dataset's EDA with the saved analysis. Model selection uses cross-validation; evaluation uses the held-out test partition.</p>
      {r.plan.reasoning&&<details className="report-details"><summary>Optional planning rationale</summary><p>{r.plan.reasoning}</p></details>}
    </section>
    <section className="surface report-section" id="report-quality">
      <div className="section-title"><ShieldCheck size={21}/><h2>2. Dataset profile & quality</h2></div>
      <div className="report-facts"><div><span>Original rows</span><strong>{fmt(profile.rows)}</strong></div><div><span>Columns</span><strong>{profile.column_count}</strong></div><div><span>Complete cells</span><strong>{fmt(profile.completeness)}%</strong></div><div><span>Duplicate rows</span><strong>{fmt(profile.duplicate_rows)}</strong></div></div>
      <p className="muted small">{fmt(profile.missing_cells)} missing cells in the original upload. Dataset previews show the first five rows.</p>
      <details className="report-details"><summary>Column statistics ({profile.column_count} columns)</summary><ReportTable headers={['Column','Type','Unique','Missing','Mean','Range']} rows={profile.columns.map(c=>[c.name,c.type,c.unique,`${c.missing} (${c.missing_pct}%)`,c.mean,c.min==null?'—':`${fmt(c.min)} – ${fmt(c.max)}`])}/></details>
      <details className="report-details"><summary>Dataset preview (5 rows)</summary><ReportTable headers={profile.columns.map(c=>c.name)} rows={profile.preview.slice(0,5).map(row=>profile.columns.map(c=>row[c.name]))}/></details>
    </section>
    <section className="report-section" id="report-eda"><div className="surface report-section-intro"><div className="section-title"><BarChart3 size={21}/><h2>3. Exploratory data analysis</h2></div><p className="muted">Inspect distributions, missing values, numeric relationships, and correlations for this dataset.</p><p className="muted small">The downloadable main report includes charts for every column, a correlation map, and a default numeric relationship when available.</p></div><EDADashboard key={job.dataset_id} datasetId={job.dataset_id} target={r.plan.target} apiKey={apiKey}/></section>
    <section className="surface report-section" id="report-preparation"><h2>4. Cleaning & feature engineering</h2><div className="report-facts"><div><span>Original rows</span><strong>{fmt(cleaning.original_rows)}</strong></div><div><span>Removed</span><strong>{fmt(cleaning.removed_rows)}</strong></div><div><span>Usable rows</span><strong>{fmt(cleaning.clean_rows)}</strong></div><div><span>Selected features</span><strong>{features.selected.length}</strong></div></div><ul>{[...cleaning.actions,...features.transformations].map((text,i)=><li key={i}>{text}</li>)}</ul><h3>Selected features</h3><div className="chip-list">{features.selected.map(name=><span key={name}>{name}</span>)}</div>{features.excluded.length>0&&<details className="report-details"><summary>Excluded features and reasons ({features.excluded.length})</summary><ReportTable headers={['Feature','Reason']} rows={features.excluded.map(c=>[c.column,c.reason])}/></details>}</section>
    <section className="surface report-section" id="report-models"><h2>5. Model selection, training & tuning</h2><p className="muted">{models.cv_folds}-fold cross-validation · {models.selection_metric} · seed {job.request.seed} · up to {job.request.tuning_iterations} tuning configurations per model</p><ReportTable headers={['Model','Family','CV score','CV std','Seconds','Status','Best parameters']} rows={models.leaderboard.map(m=>[m.name+(m.name===models.winner?' (selected)':''),m.family,m.cv_score,m.cv_std,m.seconds,m.status,m.parameters||m.error])}/><p className="muted small">The model with the strongest validation score is selected before held-out evaluation. Negative loss scores are better when closer to zero.</p></section>
    <section className="surface report-section" id="report-evaluation"><h2>6. Evaluation & critic checks</h2><p className="muted">{fmt(evaluation.train_rows)} training rows · {fmt(evaluation.test_rows)} held-out rows</p><ReportTable headers={['Metric','Selected model','Baseline','Training']} rows={metricRows.map(([name,value])=>[name.replaceAll('_',' '),value,evaluation.baseline[name],evaluation.training_metrics[name]])}/>{confusion&&<><h3>Confusion matrix</h3><p className="muted small">Rows are actual classes; columns are predictions.</p><ReportTable headers={['Actual / predicted',...evaluation.classes]} rows={confusion.map((row,i)=>[evaluation.classes[i],...row])}/></>}<h3>Validation warnings & limitations</h3><ul>{evaluation.warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul></section>
    <section className="surface report-section" id="report-shap"><h2>7. Global & local explainability</h2><p className="muted">{explainability.note||explainability.reason}</p>{explainability.global?.length>0&&<><div className="report-importance" role="img" aria-label="Top features by mean absolute SHAP">{explainability.global.slice(0,10).map(feature=><div key={feature.feature}><span title={feature.feature}>{feature.feature}</span><div><i style={{width:`${feature.mean_abs_shap/Math.max(...explainability.global.map(v=>v.mean_abs_shap),Number.EPSILON)*100}%`}}/></div><strong>{fmt(feature.mean_abs_shap)}</strong></div>)}</div><p className="muted small">{explainability.method} · {explainability.sample_rows} held-out examples · {explainability.units}. SHAP values describe associations with model predictions.</p></>}{explainability.local?.slice(0,3).map(local=><details className="report-details" key={local.row}><summary>Local explanation: row {local.row} · {local.output}</summary><p>Base {fmt(local.base_value)} + contributions {fmt(local.sum_contributions)} = prediction {fmt(local.prediction)}. Additivity residual: {fmt(local.additivity_error)}.</p><ReportTable headers={['Feature','Contribution']} rows={local.contributions.map(c=>[c.feature,c.contribution])}/></details>)}</section>
    <section className="surface report-section" id="report-recommendations"><h2>8. Recommendations & using the saved model</h2><ul>{insights.recommendations.map((text,i)=><li key={i}>{text}</li>)}</ul>{insights.llm_commentary&&<details className="report-details"><summary>Optional LLM commentary (advisory)</summary><p>{insights.llm_commentary}</p><ul>{insights.llm_recommendations?.map((text,i)=><li key={i}>{text}</li>)}</ul></details>}<h3>Prediction API</h3><p>Use the saved preprocessing pipeline with the same feature names. Test predictions from the Models page or call:</p><code className="report-endpoint">POST /api/analyses/{job.id}/predict</code><details className="report-details"><summary>Required input schema ({r.model_schema.length} features)</summary><ReportTable headers={['Feature','Type']} rows={r.model_schema.map(c=>[c.name,c.type])}/></details><p className="muted small">Validate independently before operational use. Load only trusted model files. Report exports include dataset previews; review before sharing.</p></section>
  </article>;
}

function ReportTable({headers,rows}:{headers:string[];rows:unknown[][]}){
  return <div className="table-scroll"><table><thead><tr>{headers.map((header,i)=><th key={i}>{header}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((value,j)=><td key={j}>{fmt(value)}</td>)}</tr>)}</tbody></table></div>;
}
